sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: jb9182Oh+ca+7at5AsJpf0tMxOyCnJ4lWlVQsqiHLNVIjaedQmHmFeKuvjDg0qnXmP8rB0m49hlTM93NHpNieMzn+Oztwn5JzgbNUHayRquc5xU/U+8AO5Iytl7LXfQz+tpxt1Q9j4e5DondXrwggpg/Uam1h6x2b95wYOBwelAw42dqoFNc1Ubg2sHT2tb7CKqPmdYJhrYaB2VNpfKlGvxue9O/w/g1fFGNaRTHj9jNqy3CvTllExkhp41fnWef41kffL4pkj3vE7P/Si8fSbt4O5ptxTBBdhcWtiZZ3SbmEmgGUNt8FEFRpgSnq+QuY5Ia5EHwMzRhyHw/Ghy19/3ldVGmqwwHfk/WBuWP1yc3ecFisdspyxykFc0ETv9/oCeWJeyxCStbpAkMJSNuFNfpa2a/xMUB+JPcgAqWh385mzEyYMKDHjl8aQaz5VBKAItcB1lGEWr2K4vaKJGII1Tz0Qw9nLh5vfJAwXLMopChyCifYkIM0Xy9HlsUEJLDdfs1cj9oOGDvvxa5PQgmyoaIlfJkJ3l7ZMqiNn4UEhXYAMJSfXfBZ4UH6nXC5ldAl6O29e/5zcI1NNtdMRD1vtqxpb5KtiOvC0mnL98kBQP2XQmB8qmDxcUF6dWgSTQEdGalQfEJ4kfA4l5A3nv+FKaSMAdOkOMaoNvVqNVComE=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Tempest_1540
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy